import http.server
import socketserver
import json

PORT = 8765

class MockOCRHandler(http.server.BaseHTTPRequestHandler):
    def do_POST(self):
        if self.path == '/ocr':
            # Read the request body to avoid blocking
            content_length = int(self.headers.get('Content-Length', 0))
            if content_length > 0:
                self.rfile.read(content_length)

            self.send_response(200)
            self.send_header('Content-Type', 'application/json')
            self.end_headers()
            
            # Return dummy text inside a JSON response as expected by ocr-fallback.ts
            response_data = {
                "text": "This is mock OCR text generated by the mock server for deployment testing."
            }
            self.wfile.write(json.dumps(response_data).encode('utf-8'))
        else:
            self.send_response(404)
            self.end_headers()

# Avoid 'Address already in use' errors if we restart
socketserver.TCPServer.allow_reuse_address = True

if __name__ == "__main__":
    with socketserver.TCPServer(("", PORT), MockOCRHandler) as httpd:
        print(f"Serving Mock OCR at port {PORT}")
        httpd.serve_forever()
