/**
 * Relational IR — the database projection of the semantic model.
 *
 * Generated by the Database Generator from SemanticModelIR.
 * Consumed by the SQL Generator to produce DDL, migrations, and Prisma fragments.
 */
import type { PropertyDataType } from './types';

// ────────────────────────────────────────────────────────────────────────────
// Top-level relational model
// ────────────────────────────────────────────────────────────────────────────

export interface RelationalModelIR {
  /** Source ontology version */
  ontologyVersion: number;
  /** Compiled at */
  compiledAt: string;

  tables: TableIR[];
  enums: EnumIR[];
  indexes: IndexIR[];
  foreignKeys: ForeignKeyIR[];

  /** Join tables for many-to-many relationships */
  joinTables: JoinTableIR[];

  /** Check constraints */
  checkConstraints: CheckConstraintIR[];

  /** Generated audit/history tables */
  historyTables: TableIR[];
}

// ────────────────────────────────────────────────────────────────────────────
// Table IR
// ────────────────────────────────────────────────────────────────────────────

export interface TableIR {
  /** Entity name (ontology class) */
  entity: string;
  /** SQL table name */
  tableName: string;
  /** Schema (e.g. "public" or "iscarb") */
  schema: string;
  /** Human-readable label */
  label: string;
  /** Description / comment on the table */
  description?: string;

  columns: ColumnIR[];
  primaryKey: PrimaryKeyIR;

  /** Entity type (concrete, abstract, join) */
  tableType: 'entity' | 'join' | 'history' | 'audit';

  /** Whether this table is generated by the ontology-driven pipeline */
  isGenerated: boolean;

  /** SQL DDL for this table */
  ddl?: string;
}

export interface ColumnIR {
  /** Ontology property name */
  property?: string;
  /** SQL column name */
  columnName: string;
  /** SQL data type string (e.g. "TEXT", "INTEGER", "NUMERIC(5,2)") */
  sqlType: string;
  /** Whether the column is nullable */
  nullable: boolean;
  /** Whether the column has a UNIQUE constraint */
  unique: boolean;
  /** Default value expression */
  defaultValue?: string;
  /** Description / comment */
  description?: string;

  /** Whether this is a generated column (id, timestamps) */
  isSystem: boolean;
  /** Original ontology datatype */
  ontologyDatatype?: PropertyDataType;
}

export interface PrimaryKeyIR {
  columns: string[];
  name?: string;
}

// ────────────────────────────────────────────────────────────────────────────
// Enum IR
// ────────────────────────────────────────────────────────────────────────────

export interface EnumIR {
  name: string;
  values: string[];
  /** Ontology property this enum is derived from (if any) */
  sourceProperty?: string;
}

// ────────────────────────────────────────────────────────────────────────────
// Index IR
// ────────────────────────────────────────────────────────────────────────────

export type IndexType = 'btree' | 'hash' | 'gin' | 'gist' | 'fulltext' | 'unique';

export interface IndexIR {
  name: string;
  tableName: string;
  columns: string[];
  type: IndexType;
  /** Whether this index is for vector/semantic search */
  isVectorIndex: boolean;
  /** Vector dimensions (if vector index) */
  vectorDimensions?: number;
}

// ────────────────────────────────────────────────────────────────────────────
// Foreign Key IR
// ────────────────────────────────────────────────────────────────────────────

export interface ForeignKeyIR {
  name: string;
  /** Source table and columns */
  fromTable: string;
  fromColumns: string[];
  /** Target table and columns */
  toTable: string;
  toColumns: string[];
  /** Delete rule */
  onDelete: 'CASCADE' | 'SET NULL' | 'RESTRICT' | 'NO ACTION';
  /** Update rule */
  onUpdate: 'CASCADE' | 'SET NULL' | 'RESTRICT' | 'NO ACTION';
}

// ────────────────────────────────────────────────────────────────────────────
// Join Table IR (for many-to-many)
// ────────────────────────────────────────────────────────────────────────────

export interface JoinTableIR {
  tableName: string;
  /** Relationship name */
  relationship: string;
  /** Entity on the left side */
  leftEntity: string;
  leftColumn: string;
  /** Entity on the right side */
  rightEntity: string;
  rightColumn: string;
  /** Additional columns (e.g. enrollment date, role) */
  additionalColumns: ColumnIR[];
}

// ────────────────────────────────────────────────────────────────────────────
// Check Constraint IR
// ────────────────────────────────────────────────────────────────────────────

export interface CheckConstraintIR {
  name: string;
  tableName: string;
  /** SQL expression (e.g. "cgpa >= 0 AND cgpa <= 4") */
  expression: string;
  description?: string;
}
