import { OntologyEngine, type OntologyClass, type ObjectProperty, type DatatypeProperty } from './engine';

export function createISCARBOntology(): OntologyEngine {
  const engine = new OntologyEngine();

  const classes: Omit<OntologyClass, 'equivalentClasses' | 'disjointWith' | 'restrictions' | 'annotations' | 'versionInfo'>[] = [
    { id: 'Organization', name: 'Organization', label: 'Organization', description: 'A top-level organizational entity (university, company, government body)' },
    { id: 'University', name: 'University', label: 'University', description: 'An accredited higher education institution', parentClass: 'Organization' },
    { id: 'Department', name: 'Department', label: 'Department', description: 'An academic department within a faculty', parentClass: 'Organization' },
    { id: 'Faculty', name: 'Faculty', label: 'Faculty', description: 'A faculty or college within a university', parentClass: 'Organization' },
    { id: 'Program', name: 'Program', label: 'Academic Program', description: 'An academic degree program (e.g., BSc Computer Science)' },
    { id: 'Course', name: 'Course', label: 'Course', description: 'A single course unit within an academic program' },
    { id: 'Module', name: 'Module', label: 'Course Module', description: 'A module or unit within a course' },
    { id: 'Student', name: 'Student', label: 'Student', description: 'A student enrolled in the academic system' },
    { id: 'FacultyMember', name: 'FacultyMember', label: 'Faculty Member', description: 'A faculty member who teaches or supervises' },
    { id: 'Staff', name: 'Staff', label: 'Staff', description: 'Administrative or support staff' },
    { id: 'Enrollment', name: 'Enrollment', label: 'Enrollment', description: 'A student enrollment record in a course' },
    { id: 'Assignment', name: 'Assignment', label: 'Assignment', description: 'An academic assignment given in a course' },
    { id: 'Submission', name: 'Submission', label: 'Submission', description: 'A student submission for an assignment' },
    { id: 'Grade', name: 'Grade', label: 'Grade', description: 'A grade record for a submission or assessment' },
    { id: 'Competency', name: 'Competency', label: 'Competency', description: 'A measurable competency or learning outcome' },
    { id: 'Skill', name: 'Skill', label: 'Skill', description: 'A specific skill possessed or demonstrated' },
    { id: 'Assessment', name: 'Assessment', label: 'Assessment', description: 'An assessment or evaluation event' },
    { id: 'LearningPath', name: 'LearningPath', label: 'Learning Path', description: 'A structured sequence of learning activities' },
    { id: 'CareerPath', name: 'CareerPath', label: 'Career Path', description: 'A career trajectory or roadmap for a student' },
    { id: 'ResearchProject', name: 'ResearchProject', label: 'Research Project', description: 'An academic research project' },
    { id: 'Publication', name: 'Publication', label: 'Publication', description: 'A published academic paper or article' },
    { id: 'JobPosting', name: 'JobPosting', label: 'Job Posting', description: 'An external job opportunity posted for students' },
    { id: 'Resume', name: 'Resume', label: 'Resume', description: 'A student resume or CV artifact' },
    { id: 'Notification', name: 'Notification', label: 'Notification', description: 'A system notification sent to a user' },
    { id: 'Workflow', name: 'Workflow', label: 'Workflow', description: 'An automated workflow process' },
    { id: 'Permission', name: 'Permission', label: 'Permission', description: 'A system permission or access right' },
    { id: 'Role', name: 'Role', label: 'Role', description: 'A user role with associated permissions' },
    { id: 'AcademicCalendar', name: 'AcademicCalendar', label: 'Academic Calendar', description: 'An academic calendar or scheduling period' },
    { id: 'Semester', name: 'Semester', label: 'Semester', description: 'A semester or term within an academic calendar' },
  ];

  for (const cls of classes) {
    engine.addClass(cls);
  }

  const objectProperties: ObjectProperty[] = [
    { id: 'op_enrolledIn', name: 'enrolledIn', domain: 'Student', range: 'Course', characteristics: [] },
    { id: 'op_teaches', name: 'teaches', domain: 'FacultyMember', range: 'Course', characteristics: [] },
    { id: 'op_belongsTo', name: 'belongsTo', domain: 'Student', range: 'University', characteristics: [] },
    { id: 'op_belongsToDept', name: 'belongsToDepartment', domain: 'FacultyMember', range: 'Department', characteristics: [] },
    { id: 'op_hasAssignment', name: 'hasAssignment', domain: 'Course', range: 'Assignment', characteristics: [] },
    { id: 'op_submittedBy', name: 'submittedBy', domain: 'Submission', range: 'Student', characteristics: [] },
    { id: 'op_submittedFor', name: 'submittedFor', domain: 'Submission', range: 'Assignment', characteristics: [] },
    { id: 'op_hasGrade', name: 'hasGrade', domain: 'Submission', range: 'Grade', characteristics: [] },
    { id: 'op_requiresCompetency', name: 'requiresCompetency', domain: 'Course', range: 'Competency', characteristics: [] },
    { id: 'op_demonstratesSkill', name: 'demonstratesSkill', domain: 'Student', range: 'Skill', characteristics: [] },
    { id: 'op_hasAssessment', name: 'hasAssessment', domain: 'Course', range: 'Assessment', characteristics: [] },
    { id: 'op_inLearningPath', name: 'inLearningPath', domain: 'Course', range: 'LearningPath', characteristics: [] },
    { id: 'op_hasCareerPath', name: 'hasCareerPath', domain: 'Student', range: 'CareerPath', characteristics: [] },
    { id: 'op_worksOn', name: 'worksOn', domain: 'Student', range: 'ResearchProject', characteristics: [] },
    { id: 'op_supervises', name: 'supervises', domain: 'FacultyMember', range: 'ResearchProject', characteristics: [] },
    { id: 'op_hasPublication', name: 'hasPublication', domain: 'ResearchProject', range: 'Publication', characteristics: [] },
    { id: 'op_offersJob', name: 'offersJob', domain: 'Organization', range: 'JobPosting', characteristics: [] },
    { id: 'op_matchesTo', name: 'matchesTo', domain: 'Student', range: 'JobPosting', characteristics: [] },
    { id: 'op_hasResume', name: 'hasResume', domain: 'Student', range: 'Resume', characteristics: [] },
    { id: 'op_sentTo', name: 'sentTo', domain: 'Notification', range: 'Student', characteristics: [] },
    { id: 'op_executes', name: 'executes', domain: 'Workflow', range: 'Assignment', characteristics: [] },
    { id: 'op_hasPermission', name: 'hasPermission', domain: 'Role', range: 'Permission', characteristics: [] },
    { id: 'op_assignedRole', name: 'assignedRole', domain: 'Student', range: 'Role', characteristics: [] },
    { id: 'op_inCalendar', name: 'inCalendar', domain: 'Semester', range: 'AcademicCalendar', characteristics: [] },
    { id: 'op_hasSemester', name: 'hasSemester', domain: 'Course', range: 'Semester', characteristics: [] },
    { id: 'op_partOfProgram', name: 'partOfProgram', domain: 'Course', range: 'Program', characteristics: [] },
    { id: 'op_hasModule', name: 'hasModule', domain: 'Course', range: 'Module', characteristics: [] },
    { id: 'op_inDepartment', name: 'inDepartment', domain: 'Program', range: 'Department', characteristics: [] },
    { id: 'op_inFaculty', name: 'inFaculty', domain: 'Department', range: 'Faculty', characteristics: [] },
    { id: 'op_inUniversity', name: 'inUniversity', domain: 'Faculty', range: 'University', characteristics: [] },
  ];

  for (const prop of objectProperties) {
    engine.addObjectProperty(prop);
  }

  const datatypeProperties: DatatypeProperty[] = [
    { id: 'dp_orgName', name: 'name', domain: 'Organization', datatype: 'string', required: true },
    { id: 'dp_orgCode', name: 'code', domain: 'Organization', datatype: 'string', required: true },
    { id: 'dp_universityCity', name: 'city', domain: 'University', datatype: 'string', required: false },
    { id: 'dp_studentName', name: 'name', domain: 'Student', datatype: 'string', required: true },
    { id: 'dp_studentEmail', name: 'email', domain: 'Student', datatype: 'string', required: true, pattern: '^[\\w.-]+@[\\w.-]+\\.\\w+$' },
    { id: 'dp_studentCgpa', name: 'cgpa', domain: 'Student', datatype: 'float', required: false, unit: 'GPA' },
    { id: 'dp_studentCohort', name: 'cohort', domain: 'Student', datatype: 'string', required: false },
    { id: 'dp_studentDiscoverable', name: 'discoverable', domain: 'Student', datatype: 'boolean', required: false, defaultValue: 'false' },
    { id: 'dp_facultyName', name: 'name', domain: 'FacultyMember', datatype: 'string', required: true },
    { id: 'dp_facultyEmail', name: 'email', domain: 'FacultyMember', datatype: 'string', required: true },
    { id: 'dp_facultyRank', name: 'rank', domain: 'FacultyMember', datatype: 'string', required: false, defaultValue: 'Assistant Professor' },
    { id: 'dp_courseName', name: 'name', domain: 'Course', datatype: 'string', required: true },
    { id: 'dp_courseCode', name: 'code', domain: 'Course', datatype: 'string', required: true },
    { id: 'dp_courseCredits', name: 'credits', domain: 'Course', datatype: 'integer', required: true, unit: 'credit hours' },
    { id: 'dp_moduleTitle', name: 'title', domain: 'Module', datatype: 'string', required: true },
    { id: 'dp_moduleContent', name: 'content', domain: 'Module', datatype: 'text', required: false },
    { id: 'dp_enrollmentSemester', name: 'semester', domain: 'Enrollment', datatype: 'string', required: true },
    { id: 'dp_assignmentTitle', name: 'title', domain: 'Assignment', datatype: 'string', required: true },
    { id: 'dp_assignmentDueDate', name: 'dueDate', domain: 'Assignment', datatype: 'datetime', required: true },
    { id: 'dp_assignmentMaxScore', name: 'maxScore', domain: 'Assignment', datatype: 'float', required: true },
    { id: 'dp_submissionContent', name: 'content', domain: 'Submission', datatype: 'text', required: false },
    { id: 'dp_submissionSubmittedAt', name: 'submittedAt', domain: 'Submission', datatype: 'datetime', required: true },
    { id: 'dp_gradeScore', name: 'score', domain: 'Grade', datatype: 'float', required: true, unit: 'points' },
    { id: 'dp_gradeLetter', name: 'letterGrade', domain: 'Grade', datatype: 'string', required: false },
    { id: 'dp_gradeFeedback', name: 'feedback', domain: 'Grade', datatype: 'text', required: false },
    { id: 'dp_competencyName', name: 'name', domain: 'Competency', datatype: 'string', required: true },
    { id: 'dp_competencyDescription', name: 'description', domain: 'Competency', datatype: 'text', required: false },
    { id: 'dp_skillName', name: 'name', domain: 'Skill', datatype: 'string', required: true },
    { id: 'dp_skillLevel', name: 'level', domain: 'Skill', datatype: 'integer', required: false, defaultValue: '1' },
    { id: 'dp_assessmentTitle', name: 'title', domain: 'Assessment', datatype: 'string', required: true },
    { id: 'dp_assessmentType', name: 'type', domain: 'Assessment', datatype: 'string', required: true },
    { id: 'dp_learningPathTitle', name: 'title', domain: 'LearningPath', datatype: 'string', required: true },
    { id: 'dp_careerPathTitle', name: 'title', domain: 'CareerPath', datatype: 'string', required: true },
    { id: 'dp_careerPathTarget', name: 'targetTitle', domain: 'CareerPath', datatype: 'string', required: false },
    { id: 'dp_researchTitle', name: 'title', domain: 'ResearchProject', datatype: 'string', required: true },
    { id: 'dp_researchDescription', name: 'description', domain: 'ResearchProject', datatype: 'text', required: false },
    { id: 'dp_pubTitle', name: 'title', domain: 'Publication', datatype: 'string', required: true },
    { id: 'dp_pubJournal', name: 'journal', domain: 'Publication', datatype: 'string', required: false },
    { id: 'dp_pubDoi', name: 'doi', domain: 'Publication', datatype: 'string', required: false },
    { id: 'dp_jobTitle', name: 'title', domain: 'JobPosting', datatype: 'string', required: true },
    { id: 'dp_jobEmployer', name: 'employer', domain: 'JobPosting', datatype: 'string', required: true },
    { id: 'dp_jobSalary', name: 'salaryRange', domain: 'JobPosting', datatype: 'string', required: false },
    { id: 'dp_resumeTitle', name: 'title', domain: 'Resume', datatype: 'string', required: true },
    { id: 'dp_resumeData', name: 'data', domain: 'Resume', datatype: 'json', required: true },
    { id: 'dp_notifTitle', name: 'title', domain: 'Notification', datatype: 'string', required: true },
    { id: 'dp_notifBody', name: 'body', domain: 'Notification', datatype: 'text', required: false },
    { id: 'dp_notifRead', name: 'read', domain: 'Notification', datatype: 'boolean', required: false, defaultValue: 'false' },
    { id: 'dp_workflowName', name: 'name', domain: 'Workflow', datatype: 'string', required: true },
    { id: 'dp_workflowStatus', name: 'status', domain: 'Workflow', datatype: 'string', required: true, defaultValue: 'active' },
    { id: 'dp_permName', name: 'name', domain: 'Permission', datatype: 'string', required: true },
    { id: 'dp_permAction', name: 'action', domain: 'Permission', datatype: 'string', required: true },
    { id: 'dp_roleName', name: 'name', domain: 'Role', datatype: 'string', required: true },
    { id: 'dp_roleDescription', name: 'description', domain: 'Role', datatype: 'text', required: false },
    { id: 'dp_calName', name: 'name', domain: 'AcademicCalendar', datatype: 'string', required: true },
    { id: 'dp_calYear', name: 'academicYear', domain: 'AcademicCalendar', datatype: 'integer', required: true },
    { id: 'dp_semName', name: 'name', domain: 'Semester', datatype: 'string', required: true },
    { id: 'dp_semStartDate', name: 'startDate', domain: 'Semester', datatype: 'date', required: true },
    { id: 'dp_semEndDate', name: 'endDate', domain: 'Semester', datatype: 'date', required: true },
    { id: 'dp_programName', name: 'name', domain: 'Program', datatype: 'string', required: true },
    { id: 'dp_programLevel', name: 'degreeLevel', domain: 'Program', datatype: 'string', required: false },
    { id: 'dp_staffName', name: 'name', domain: 'Staff', datatype: 'string', required: true },
    { id: 'dp_staffEmail', name: 'email', domain: 'Staff', datatype: 'string', required: true },
  ];

  for (const prop of datatypeProperties) {
    engine.addDatatypeProperty(prop);
  }

  return engine;
}
