/**
 * Mapper registry — maps entity types to their RDF mappers.
 * AUTO-GENERATED by scripts/generate-rdf-mappers.ts — do not edit by hand.
 */
import type { RdfMapper } from "./types";

// Already-handled mappers
import { userMapper } from "./user.mapper";
import { roleMapper } from "./role.mapper";
import { permissionMapper } from "./permission.mapper";
import { abacPolicyMapper } from "./abac-policy.mapper";
import { studentMapper } from "./student.mapper";
import { courseMapper } from "./course.mapper";
import { facultyMapper } from "./faculty.mapper";
import { assessmentMapper } from "./assessment.mapper";
import { competencyMapper } from "./competency.mapper";
import { assessmentResponseMapper } from "./assessment-response.mapper";
import { employabilityProfileMapper } from "./employability-profile.mapper";
import * as assessmentSnapshotMapper from "./assessment-snapshot.mapper";
import { universityMapper } from "./university.mapper";
import { enrollmentMapper } from "./enrollment.mapper";
import { semesterMapper } from "./semester.mapper";

// Auto-generated mappers
import { unitMapper } from "./unit.mapper";
import { aiPromptMapper } from "./ai-prompt.mapper";
import { attendanceRecordMapper } from "./attendance-record.mapper";
import { activeParticipationMapper } from "./active-participation.mapper";
import { gradeAdjustmentMapper } from "./grade-adjustment.mapper";
import { deanNotificationMapper } from "./dean-notification.mapper";
import { simulationMapper } from "./simulation.mapper";
import { projectMapper } from "./project.mapper";
import { careerMappingMapper } from "./career-mapping.mapper";
import { studentAgentMapper } from "./student-agent.mapper";
import { challengeMapper } from "./challenge.mapper";
import { challengeTeamMapper } from "./challenge-team.mapper";
import { challengeTeamMemberMapper } from "./challenge-team-member.mapper";
import { marketSignalMapper } from "./market-signal.mapper";
import { assessmentModuleMapper } from "./assessment-module.mapper";
import { scedFieldMapper } from "./sced-field.mapper";
import { ssccoOccupationMapper } from "./sscco-occupation.mapper";
import { equityLedgerMapper } from "./equity-ledger.mapper";
import { equityEventMapper } from "./equity-event.mapper";
import { careerPathMapper } from "./career-path.mapper";
import { careerStageMapper } from "./career-stage.mapper";
import { portfolioReviewMapper } from "./portfolio-review.mapper";
import { jobPostingMapper } from "./job-posting.mapper";
import { jobMatchMapper } from "./job-match.mapper";
import { fundingProgramMapper } from "./funding-program.mapper";
import { jobOfferMapper } from "./job-offer.mapper";
import { fundingSaveMapper } from "./funding-save.mapper";
import { studentBadgeMapper } from "./student-badge.mapper";
import { r2CartifactMapper } from "./r2-cartifact.mapper";
import { studentOnboardingMapper } from "./student-onboarding.mapper";
import { onboardingTaskMapper } from "./onboarding-task.mapper";
import { recruiterMapper } from "./recruiter.mapper";
import { talentPoolMapper } from "./talent-pool.mapper";
import { talentPoolMemberMapper } from "./talent-pool-member.mapper";
import { pipelineStageMapper } from "./pipeline-stage.mapper";
import { recruiterActivityMapper } from "./recruiter-activity.mapper";
import { graduationChecklistMapper } from "./graduation-checklist.mapper";
import { skillExplorationMapper } from "./skill-exploration.mapper";
import { careerCardMapper } from "./career-card.mapper";
import { careerInterestMapper } from "./career-interest.mapper";
import { skillProgressMapper } from "./skill-progress.mapper";
import { internshipMapper } from "./internship.mapper";
import { interviewPrepMapper } from "./interview-prep.mapper";
import { communityPostMapper } from "./community-post.mapper";
import { communityReplyMapper } from "./community-reply.mapper";
import { mentorProfileMapper } from "./mentor-profile.mapper";
import { mentorshipSessionMapper } from "./mentorship-session.mapper";
import { enrichmentSourceMapper } from "./enrichment-source.mapper";
import { enrichmentContentMapper } from "./enrichment-content.mapper";
import { hackathonMapper } from "./hackathon.mapper";
import { hackathonRegistrationMapper } from "./hackathon-registration.mapper";
import { hackathonTeamMapper } from "./hackathon-team.mapper";
import { hackathonTeamMemberMapper } from "./hackathon-team-member.mapper";
import { certificationMapper } from "./certification.mapper";
import { courseConceptMapper } from "./course-concept.mapper";
import { certificationConceptMapper } from "./certification-concept.mapper";
import { conceptPrerequisiteMapper } from "./concept-prerequisite.mapper";
import { consentRecordMapper } from "./consent-record.mapper";
import { issuedCredentialMapper } from "./issued-credential.mapper";
import { auditLogMapper } from "./audit-log.mapper";
import { notificationMapper } from "./notification.mapper";
import { pushSubscriptionMapper } from "./push-subscription.mapper";
import { studentAgentMessageMapper } from "./student-agent-message.mapper";
import { portfolioMapper } from "./portfolio.mapper";
import { portfolioEntryMapper } from "./portfolio-entry.mapper";
import { portfolioAchievementMapper } from "./portfolio-achievement.mapper";
import { portfolioSkillMapper } from "./portfolio-skill.mapper";
import { skillEndorsementMapper } from "./skill-endorsement.mapper";
import { portfolioCareerProfileMapper } from "./portfolio-career-profile.mapper";
import { portfolioShareLinkMapper } from "./portfolio-share-link.mapper";
import { portfolioViewMapper } from "./portfolio-view.mapper";
import { knowledgeBaseTopicMapper } from "./knowledge-base-topic.mapper";
import { knowledgeBaseArticleMapper } from "./knowledge-base-article.mapper";
import { knowledgeBaseViewMapper } from "./knowledge-base-view.mapper";
import { knowledgeBaseFeedbackMapper } from "./knowledge-base-feedback.mapper";
import { knowledgeBaseSearchMapper } from "./knowledge-base-search.mapper";
import { assessmentQuestionMapper } from "./assessment-question.mapper";
import { assessmentSubmissionMapper } from "./assessment-submission.mapper";
import { assessmentQuestionResponseMapper } from "./assessment-question-response.mapper";
import { rubricMapper } from "./rubric.mapper";
import { rubricCriterionMapper } from "./rubric-criterion.mapper";
import { assessmentScoreMapper } from "./assessment-score.mapper";
import { calibrationSessionMapper } from "./calibration-session.mapper";
import { calibrationScoreAdjustmentMapper } from "./calibration-score-adjustment.mapper";
import { researchRequestMapper } from "./research-request.mapper";
import { datasetMapper } from "./dataset.mapper";
import { datasetAccessMapper } from "./dataset-access.mapper";
import { researchOutcomeMapper } from "./research-outcome.mapper";
import { complianceCheckMapper } from "./compliance-check.mapper";
import { researchAnalyticsMapper } from "./research-analytics.mapper";
import { researchReportMapper } from "./research-report.mapper";
import { workflowMapper } from "./workflow.mapper";
import { workflowStepMapper } from "./workflow-step.mapper";
import { workflowExecutionMapper } from "./workflow-execution.mapper";
import { workflowStepExecutionMapper } from "./workflow-step-execution.mapper";
import { workflowApprovalMapper } from "./workflow-approval.mapper";
import { workflowTemplateMapper } from "./workflow-template.mapper";
import { workflowTriggerMapper } from "./workflow-trigger.mapper";
import { workflowScheduleMapper } from "./workflow-schedule.mapper";
import { messageMapper } from "./message.mapper";
import { conversationMapper } from "./conversation.mapper";
import { announcementMapper } from "./announcement.mapper";
import { calendarEventMapper } from "./calendar-event.mapper";
import { calendarRegistrationMapper } from "./calendar-registration.mapper";
import { notificationPreferenceMapper } from "./notification-preference.mapper";
import { messageTemplateMapper } from "./message-template.mapper";
import { notificationLogMapper } from "./notification-log.mapper";
import { jobOpeningMapper } from "./job-opening.mapper";
import { candidateSubmissionMapper } from "./candidate-submission.mapper";
import { jobTemplateMapper } from "./job-template.mapper";
import { candidateEvaluationMapper } from "./candidate-evaluation.mapper";
import { interviewMapper } from "./interview.mapper";
import { offerMapper } from "./offer.mapper";
import { reportMapper } from "./report.mapper";
import { reportExecutionMapper } from "./report-execution.mapper";
import { reportScheduleMapper } from "./report-schedule.mapper";
import { reportExportMapper } from "./report-export.mapper";
import { reportMetricMapper } from "./report-metric.mapper";
import { reportDimensionMapper } from "./report-dimension.mapper";
import { reportTemplateMapper } from "./report-template.mapper";
import { reportAlertMapper } from "./report-alert.mapper";
import { countryMapper } from "./country.mapper";
import { governmentMapper } from "./government.mapper";
import { organizationMapper } from "./organization.mapper";
import { organizationSettingsMapper } from "./organization-settings.mapper";
import { organizationInvitationMapper } from "./organization-invitation.mapper";
import { rdfSyncStateMapper } from "./rdf-sync-state.mapper";
import { campusMapper } from "./campus.mapper";
import { orgFacultyMapper } from "./org-faculty.mapper";
import { departmentMapper } from "./department.mapper";
import { academicProgramMapper } from "./academic-program.mapper";
import { orgTeamMapper } from "./org-team.mapper";
import { organizationHierarchyMapper } from "./organization-hierarchy.mapper";
import { programMapper } from "./program.mapper";
import { teamMapper } from "./team.mapper";
import { groupMapper } from "./group.mapper";
import { groupMemberMapper } from "./group-member.mapper";
import { activityTimelineMapper } from "./activity-timeline.mapper";
import { competencyFrameworkMapper } from "./competency-framework.mapper";
import { competencyDefinitionMapper } from "./competency-definition.mapper";
import { studentCompetencyGraphMapper } from "./student-competency-graph.mapper";
import { humanDevelopmentTimelineMapper } from "./human-development-timeline.mapper";
import { developmentPlanMapper } from "./development-plan.mapper";
import { planGoalMapper } from "./plan-goal.mapper";
import { learningSessionMapper } from "./learning-session.mapper";
import { reflectionJournalMapper } from "./reflection-journal.mapper";
import { habitTrackerMapper } from "./habit-tracker.mapper";
import { habitCompletionMapper } from "./habit-completion.mapper";
import { wellnessIndicatorMapper } from "./wellness-indicator.mapper";
import { buildingMapper } from "./building.mapper";
import { floorMapper } from "./floor.mapper";
import { roomMapper } from "./room.mapper";
import { assetMapper } from "./asset.mapper";
import { maintenanceLogMapper } from "./maintenance-log.mapper";
import { bookingMapper } from "./booking.mapper";
import { policyMapper } from "./policy.mapper";
import { procedureMapper } from "./procedure.mapper";
import { organizationComplianceCheckMapper } from "./organization-compliance-check.mapper";
import { riskMapper } from "./risk.mapper";
import { complianceReportMapper } from "./compliance-report.mapper";
import { incidentMapper } from "./incident.mapper";
import { approvalMapper } from "./approval.mapper";
import { committeeMapper } from "./committee.mapper";
import { jobTitleMapper } from "./job-title.mapper";
import { positionMapper } from "./position.mapper";
import { reportingStructureMapper } from "./reporting-structure.mapper";
import { costCenterMapper } from "./cost-center.mapper";
import { knowledgeDocumentMapper } from "./knowledge-document.mapper";
import { documentVersionMapper } from "./document-version.mapper";
import { documentApprovalMapper } from "./document-approval.mapper";
import { documentCommentMapper } from "./document-comment.mapper";
import { wikiPageMapper } from "./wiki-page.mapper";
import { wikiRevisionMapper } from "./wiki-revision.mapper";
import { noteMapper } from "./note.mapper";
import { noteShareMapper } from "./note-share.mapper";
import { researchPaperMapper } from "./research-paper.mapper";
import { researchDatasetMapper } from "./research-dataset.mapper";
import { researchProtocolMapper } from "./research-protocol.mapper";
import { citationMapper } from "./citation.mapper";
import { knowledgeSourceMapper } from "./knowledge-source.mapper";
import { knowledgeIngestionJobMapper } from "./knowledge-ingestion-job.mapper";
import { knowledgeQualityCheckMapper } from "./knowledge-quality-check.mapper";
import { knowledgeVersionMapper } from "./knowledge-version.mapper";
import { knowledgeApprovalMapper } from "./knowledge-approval.mapper";
import { knowledgeAutomationRuleMapper } from "./knowledge-automation-rule.mapper";
import { knowledgeAutomationLogMapper } from "./knowledge-automation-log.mapper";
import { aiRequestLogMapper } from "./ai-request-log.mapper";
import { aiModelMapper } from "./ai-model.mapper";
import { aiModelVersionMapper } from "./ai-model-version.mapper";
import { aiModelMetricMapper } from "./ai-model-metric.mapper";
import { aiAgentMapper } from "./ai-agent.mapper";
import { aiAgentSessionMapper } from "./ai-agent-session.mapper";
import { aiAgentMessageMapper } from "./ai-agent-message.mapper";
import { aiMemoryMapper } from "./ai-memory.mapper";
import { aiPlanMapper } from "./ai-plan.mapper";
import { aiPlanStepMapper } from "./ai-plan-step.mapper";
import { aiReflectionMapper } from "./ai-reflection.mapper";
import { aiToolMapper } from "./ai-tool.mapper";
import { aiToolExecutionMapper } from "./ai-tool-execution.mapper";
import { aiEvaluationMapper } from "./ai-evaluation.mapper";
import { aiFeedbackMapper } from "./ai-feedback.mapper";
import { aiAlertMapper } from "./ai-alert.mapper";
import { aiMetricMapper } from "./ai-metric.mapper";
import { commentMapper } from "./comment.mapper";
import { discussionMapper } from "./discussion.mapper";
import { discussionReplyMapper } from "./discussion-reply.mapper";
import { activityFeedMapper } from "./activity-feed.mapper";
import { emailTemplateMapper } from "./email-template.mapper";
import { emailLogMapper } from "./email-log.mapper";
import { academicYearMapper } from "./academic-year.mapper";
import { termMapper } from "./term.mapper";
import { academicSectionMapper } from "./academic-section.mapper";
import { studentCohortMapper } from "./student-cohort.mapper";
import { curriculumMapper } from "./curriculum.mapper";
import { curriculumCourseMapper } from "./curriculum-course.mapper";
import { degreeRequirementMapper } from "./degree-requirement.mapper";
import { academicRegulationMapper } from "./academic-regulation.mapper";
import { courseOutcomeMapper } from "./course-outcome.mapper";
import { prerequisiteMapper } from "./prerequisite.mapper";
import { courseResourceMapper } from "./course-resource.mapper";
import { academicModuleMapper } from "./academic-module.mapper";
import { conceptMapper } from "./concept.mapper";
import { topicMapper } from "./topic.mapper";
import { lessonMapper } from "./lesson.mapper";
import { learningObjectiveMapper } from "./learning-objective.mapper";
import { timetableMapper } from "./timetable.mapper";
import { timetableSlotMapper } from "./timetable-slot.mapper";
import { examinationScheduleMapper } from "./examination-schedule.mapper";
import { creditRuleMapper } from "./credit-rule.mapper";
import { academicStandingMapper } from "./academic-standing.mapper";
import { graduationProgressMapper } from "./graduation-progress.mapper";
import { academicResourceMapper } from "./academic-resource.mapper";
import { readingListMapper } from "./reading-list.mapper";
import { academicPolicyMapper } from "./academic-policy.mapper";
import { courseAllocationMapper } from "./course-allocation.mapper";
import { waitlistMapper } from "./waitlist.mapper";
import { courseRegistrationMapper } from "./course-registration.mapper";
import { learningJourneyMapper } from "./learning-journey.mapper";
import { learningMilestoneMapper } from "./learning-milestone.mapper";
import { dailyLearningGoalMapper } from "./daily-learning-goal.mapper";
import { weeklyLearningGoalMapper } from "./weekly-learning-goal.mapper";
import { monthlyLearningGoalMapper } from "./monthly-learning-goal.mapper";
import { flashcardDeckMapper } from "./flashcard-deck.mapper";
import { flashcardMapper } from "./flashcard.mapper";
import { flashcardReviewMapper } from "./flashcard-review.mapper";
import { studySessionMapper } from "./study-session.mapper";
import { studyPlanMapper } from "./study-plan.mapper";
import { studyReminderMapper } from "./study-reminder.mapper";
import { learningMemoryMapper } from "./learning-memory.mapper";
import { knowledgeGapMapper } from "./knowledge-gap.mapper";
import { spacedRepetitionItemMapper } from "./spaced-repetition-item.mapper";
import { masteryPredictionMapper } from "./mastery-prediction.mapper";
import { learningStreakMapper } from "./learning-streak.mapper";
import { experiencePointsMapper } from "./experience-points.mapper";
import { learningChallengeMapper } from "./learning-challenge.mapper";
import { peerLearningGroupMapper } from "./peer-learning-group.mapper";
import { digitalCredentialMapper } from "./digital-credential.mapper";
import { academicTranscriptMapper } from "./academic-transcript.mapper";
import { aiexplainRequestMapper } from "./aiexplain-request.mapper";
import { aigeneratedQuizMapper } from "./aigenerated-quiz.mapper";
import { aistudyRecommendationMapper } from "./aistudy-recommendation.mapper";
import { ailearningInsightMapper } from "./ailearning-insight.mapper";
import { generatedQuestionMapper } from "./generated-question.mapper";
import { researchProjectMapper } from "./research-project.mapper";
import { researchTaskMapper } from "./research-task.mapper";
import { researchNotebookMapper } from "./research-notebook.mapper";
import { researchGoalMapper } from "./research-goal.mapper";
import { paperCollectionMapper } from "./paper-collection.mapper";
import { citationNetworkMapper } from "./citation-network.mapper";
import { researchTrendMapper } from "./research-trend.mapper";
import { researchSummaryMapper } from "./research-summary.mapper";
import { readingListResearchMapper } from "./reading-list-research.mapper";
import { researchHypothesisMapper } from "./research-hypothesis.mapper";
import { experimentDesignResearchMapper } from "./experiment-design-research.mapper";
import { peerReviewRecordMapper } from "./peer-review-record.mapper";
import { experimentMapper } from "./experiment.mapper";
import { experimentVariableMapper } from "./experiment-variable.mapper";
import { experimentResultMapper } from "./experiment-result.mapper";
import { experimentVersionMapper } from "./experiment-version.mapper";
import { protocolTemplateMapper } from "./protocol-template.mapper";
import { datasetVersionMapper } from "./dataset-version.mapper";
import { datasetAnnotationMapper } from "./dataset-annotation.mapper";
import { datasetValidationRuleMapper } from "./dataset-validation-rule.mapper";
import { publicationMapper } from "./publication.mapper";
import { submissionTrackerMapper } from "./submission-tracker.mapper";
import { journalRecommendationMapper } from "./journal-recommendation.mapper";
import { referenceListItemMapper } from "./reference-list-item.mapper";
import { patentMapper } from "./patent.mapper";
import { ideaSubmissionMapper } from "./idea-submission.mapper";
import { innovationPipelineMapper } from "./innovation-pipeline.mapper";
import { technologyTransferMapper } from "./technology-transfer.mapper";
import { grantOpportunityMapper } from "./grant-opportunity.mapper";
import { grantApplicationMapper } from "./grant-application.mapper";
import { researchTeamMapper } from "./research-team.mapper";
import { researchCommentMapper } from "./research-comment.mapper";
import { expertNetworkMapper } from "./expert-network.mapper";
import { publicationMetricMapper } from "./publication-metric.mapper";
import { researchImpactScoreMapper } from "./research-impact-score.mapper";
import { researchFundingMetricMapper } from "./research-funding-metric.mapper";
import { careerProfileMapper } from "./career-profile.mapper";
import { careerGoalMapper } from "./career-goal.mapper";
import { interviewSessionMapper } from "./interview-session.mapper";
import { alumniMapper } from "./alumni.mapper";
import { alumniConnectionMapper } from "./alumni-connection.mapper";
import { marketplaceListingMapper } from "./marketplace-listing.mapper";
import { careerIntelligenceSnapshotMapper } from "./career-intelligence-snapshot.mapper";
import { facultyProfileMapper } from "./faculty-profile.mapper";
import { facultyBriefingMapper } from "./faculty-briefing.mapper";
import { teachingPlanMapper } from "./teaching-plan.mapper";
import { learningResourceMapper } from "./learning-resource.mapper";
import { contentItemMapper } from "./content-item.mapper";
import { teachingTimelineMapper } from "./teaching-timeline.mapper";
import { studentAlertMapper } from "./student-alert.mapper";
import { studentRecommendationMapper } from "./student-recommendation.mapper";
import { facultyMenteeMapper } from "./faculty-mentee.mapper";
import { advisingSessionMapper } from "./advising-session.mapper";
import { goalTrackingMapper } from "./goal-tracking.mapper";
import { facultyPublicationMapper } from "./faculty-publication.mapper";
import { facultyCertificationMapper } from "./faculty-certification.mapper";
import { facultyAwardMapper } from "./faculty-award.mapper";
import { facultyWorkshopMapper } from "./faculty-workshop.mapper";
import { facultyTrainingMapper } from "./faculty-training.mapper";
import { departmentDiscussionMapper } from "./department-discussion.mapper";
import { sharedResourceMapper } from "./shared-resource.mapper";
import { facultyWorkloadMapper } from "./faculty-workload.mapper";
import { leaveRequestMapper } from "./leave-request.mapper";
import { facultyTimetableMapper } from "./faculty-timetable.mapper";
import { committeeAssignmentMapper } from "./committee-assignment.mapper";
import { facultyNoteMapper } from "./faculty-note.mapper";
import { facultyBookmarkMapper } from "./faculty-bookmark.mapper";
import { savedPromptMapper } from "./saved-prompt.mapper";
import { predictionMapper } from "./prediction.mapper";
import { intelligenceRecommendationMapper } from "./intelligence-recommendation.mapper";
import { dataQualityRecordMapper } from "./data-quality-record.mapper";
import { dataLineageRecordMapper } from "./data-lineage-record.mapper";
import { benchmarkRecordMapper } from "./benchmark-record.mapper";
import { intelligenceReportMapper } from "./intelligence-report.mapper";
import { whiteLabelConfigMapper } from "./white-label-config.mapper";
import { institutionCollaborationMapper } from "./institution-collaboration.mapper";
import { betaProgramMapper } from "./beta-program.mapper";
import { betaEnrollmentMapper } from "./beta-enrollment.mapper";
import { localizationEntryMapper } from "./localization-entry.mapper";
import { orgAcademicCalendarMapper } from "./org-academic-calendar.mapper";
import { orgSemesterMapper } from "./org-semester.mapper";
import { studentEventMapper } from "./student-event.mapper";
import { competencyEvidenceMapper } from "./competency-evidence.mapper";
import { airecommendationMapper } from "./airecommendation.mapper";
import { aitutoringSessionMapper } from "./aitutoring-session.mapper";
import { aicontentGenerationMapper } from "./aicontent-generation.mapper";
import { studentLearningProfileMapper } from "./student-learning-profile.mapper";
import { aiinterventionCampaignMapper } from "./aiintervention-campaign.mapper";
import { adaptiveDifficultyLevelMapper } from "./adaptive-difficulty-level.mapper";
import { resumeAiReviewMapper } from "./resume-ai-review.mapper";
import { ontologyVersionMapper } from "./ontology-version.mapper";
import { successMetricsMapper } from "./success-metrics.mapper";
import { studentGoalMapper } from "./student-goal.mapper";
import { productivitySessionMapper } from "./productivity-session.mapper";
import { riskIndicatorMapper } from "./risk-indicator.mapper";
import { readinessAssessmentMapper } from "./readiness-assessment.mapper";
import { studentAchievementMapper } from "./student-achievement.mapper";
import { studentTaskMapper } from "./student-task.mapper";
import { simulationScenarioMapper } from "./simulation-scenario.mapper";
import { capstoneProjectMapper } from "./capstone-project.mapper";
import { successCoachSessionMapper } from "./success-coach-session.mapper";
import { jobApplicationMapper } from "./job-application.mapper";

import { placementMapper } from "./placement.mapper";
import { professionalNetworkMapper } from "./professional-network.mapper";
import { networkingEventMapper } from "./networking-event.mapper";
import { fundingApplicationMapper } from "./funding-application.mapper";
import { careerDevelopmentPlanMapper } from "./career-development-plan.mapper";
import { careerResourceAccessMapper } from "./career-resource-access.mapper";
import { careerAiinsightMapper } from "./career-aiinsight.mapper";
import { careerMockInterviewMapper } from "./career-mock-interview.mapper";
import { jobAlertSubscriptionMapper } from "./job-alert-subscription.mapper";

/** Registry of all entity mappers */
const mapperRegistry: Record<string, RdfMapper> = {
  // Pre-existing
  User: userMapper,
  Role: roleMapper,
  Permission: permissionMapper,
  AbacPolicy: abacPolicyMapper,
  Student: studentMapper,
  Course: courseMapper,
  Faculty: facultyMapper,
  Assessment: assessmentMapper,
  Competency: competencyMapper,
  Concept: competencyMapper,
  AssessmentResponse: assessmentResponseMapper,
  EmployabilityProfile: employabilityProfileMapper,
  AssessmentSnapshot: assessmentSnapshotMapper,
  University: universityMapper,
  Enrollment: enrollmentMapper,
  Semester: semesterMapper,

  // Auto-generated
  Unit: unitMapper,
  AiPrompt: aiPromptMapper,
  AttendanceRecord: attendanceRecordMapper,
  ActiveParticipation: activeParticipationMapper,
  GradeAdjustment: gradeAdjustmentMapper,
  DeanNotification: deanNotificationMapper,
  Simulation: simulationMapper,
  Project: projectMapper,
  CareerMapping: careerMappingMapper,
  StudentAgent: studentAgentMapper,
  Challenge: challengeMapper,
  ChallengeTeam: challengeTeamMapper,
  ChallengeTeamMember: challengeTeamMemberMapper,
  MarketSignal: marketSignalMapper,
  AssessmentModule: assessmentModuleMapper,
  ScedField: scedFieldMapper,
  SsccoOccupation: ssccoOccupationMapper,
  EquityLedger: equityLedgerMapper,
  EquityEvent: equityEventMapper,
  CareerPath: careerPathMapper,
  CareerStage: careerStageMapper,
  PortfolioReview: portfolioReviewMapper,
  JobPosting: jobPostingMapper,
  JobMatch: jobMatchMapper,
  FundingProgram: fundingProgramMapper,
  FundingSave: fundingSaveMapper,
  StudentBadge: studentBadgeMapper,
  R2CArtifact: r2CartifactMapper,
  StudentOnboarding: studentOnboardingMapper,
  OnboardingTask: onboardingTaskMapper,
  Recruiter: recruiterMapper,
  TalentPool: talentPoolMapper,
  TalentPoolMember: talentPoolMemberMapper,
  PipelineStage: pipelineStageMapper,
  RecruiterActivity: recruiterActivityMapper,
  GraduationChecklist: graduationChecklistMapper,
  SkillExploration: skillExplorationMapper,
  CareerCard: careerCardMapper,
  CareerInterest: careerInterestMapper,
  SkillProgress: skillProgressMapper,
  Internship: internshipMapper,
  InterviewPrep: interviewPrepMapper,
  CommunityPost: communityPostMapper,
  CommunityReply: communityReplyMapper,
  MentorProfile: mentorProfileMapper,
  MentorshipSession: mentorshipSessionMapper,
  EnrichmentSource: enrichmentSourceMapper,
  EnrichmentContent: enrichmentContentMapper,
  Hackathon: hackathonMapper,
  HackathonRegistration: hackathonRegistrationMapper,
  HackathonTeam: hackathonTeamMapper,
  HackathonTeamMember: hackathonTeamMemberMapper,
  Certification: certificationMapper,
  CourseConcept: courseConceptMapper,
  CertificationConcept: certificationConceptMapper,
  ConceptPrerequisite: conceptPrerequisiteMapper,
  ConsentRecord: consentRecordMapper,
  IssuedCredential: issuedCredentialMapper,
  AuditLog: auditLogMapper,
  Notification: notificationMapper,
  PushSubscription: pushSubscriptionMapper,
  StudentAgentMessage: studentAgentMessageMapper,
  Portfolio: portfolioMapper,
  PortfolioEntry: portfolioEntryMapper,
  PortfolioAchievement: portfolioAchievementMapper,
  PortfolioSkill: portfolioSkillMapper,
  SkillEndorsement: skillEndorsementMapper,
  PortfolioCareerProfile: portfolioCareerProfileMapper,
  PortfolioShareLink: portfolioShareLinkMapper,
  PortfolioView: portfolioViewMapper,
  KnowledgeBaseTopic: knowledgeBaseTopicMapper,
  KnowledgeBaseArticle: knowledgeBaseArticleMapper,
  KnowledgeBaseView: knowledgeBaseViewMapper,
  KnowledgeBaseFeedback: knowledgeBaseFeedbackMapper,
  KnowledgeBaseSearch: knowledgeBaseSearchMapper,
  AssessmentQuestion: assessmentQuestionMapper,
  AssessmentSubmission: assessmentSubmissionMapper,
  AssessmentQuestionResponse: assessmentQuestionResponseMapper,
  Rubric: rubricMapper,
  RubricCriterion: rubricCriterionMapper,
  AssessmentScore: assessmentScoreMapper,
  CalibrationSession: calibrationSessionMapper,
  CalibrationScoreAdjustment: calibrationScoreAdjustmentMapper,
  ResearchRequest: researchRequestMapper,
  Dataset: datasetMapper,
  DatasetAccess: datasetAccessMapper,
  ResearchOutcome: researchOutcomeMapper,
  ComplianceCheck: complianceCheckMapper,
  ResearchAnalytics: researchAnalyticsMapper,
  ResearchReport: researchReportMapper,
  Workflow: workflowMapper,
  WorkflowStep: workflowStepMapper,
  WorkflowExecution: workflowExecutionMapper,
  WorkflowStepExecution: workflowStepExecutionMapper,
  WorkflowApproval: workflowApprovalMapper,
  WorkflowTemplate: workflowTemplateMapper,
  WorkflowTrigger: workflowTriggerMapper,
  WorkflowSchedule: workflowScheduleMapper,
  Message: messageMapper,
  Conversation: conversationMapper,
  Announcement: announcementMapper,
  CalendarEvent: calendarEventMapper,
  CalendarRegistration: calendarRegistrationMapper,
  NotificationPreference: notificationPreferenceMapper,
  MessageTemplate: messageTemplateMapper,
  NotificationLog: notificationLogMapper,
  JobOpening: jobOpeningMapper,
  CandidateSubmission: candidateSubmissionMapper,
  JobTemplate: jobTemplateMapper,
  CandidateEvaluation: candidateEvaluationMapper,
  Interview: interviewMapper,
  Offer: offerMapper,
  Report: reportMapper,
  ReportExecution: reportExecutionMapper,
  ReportSchedule: reportScheduleMapper,
  ReportExport: reportExportMapper,
  ReportMetric: reportMetricMapper,
  ReportDimension: reportDimensionMapper,
  ReportTemplate: reportTemplateMapper,
  ReportAlert: reportAlertMapper,
  Country: countryMapper,
  Government: governmentMapper,
  Organization: organizationMapper,
  OrganizationSettings: organizationSettingsMapper,
  OrganizationInvitation: organizationInvitationMapper,
  RdfSyncState: rdfSyncStateMapper,
  Campus: campusMapper,
  OrgFaculty: orgFacultyMapper,
  Department: departmentMapper,
  AcademicProgram: academicProgramMapper,
  OrgTeam: orgTeamMapper,
  OrganizationHierarchy: organizationHierarchyMapper,
  Program: programMapper,
  Team: teamMapper,
  Group: groupMapper,
  GroupMember: groupMemberMapper,
  ActivityTimeline: activityTimelineMapper,
  CompetencyFramework: competencyFrameworkMapper,
  CompetencyDefinition: competencyDefinitionMapper,
  StudentCompetencyGraph: studentCompetencyGraphMapper,
  HumanDevelopmentTimeline: humanDevelopmentTimelineMapper,
  DevelopmentPlan: developmentPlanMapper,
  PlanGoal: planGoalMapper,
  LearningSession: learningSessionMapper,
  ReflectionJournal: reflectionJournalMapper,
  HabitTracker: habitTrackerMapper,
  HabitCompletion: habitCompletionMapper,
  WellnessIndicator: wellnessIndicatorMapper,
  Building: buildingMapper,
  Floor: floorMapper,
  Room: roomMapper,
  Asset: assetMapper,
  MaintenanceLog: maintenanceLogMapper,
  Booking: bookingMapper,
  Policy: policyMapper,
  Procedure: procedureMapper,
  OrganizationComplianceCheck: organizationComplianceCheckMapper,
  Risk: riskMapper,
  ComplianceReport: complianceReportMapper,
  Incident: incidentMapper,
  Approval: approvalMapper,
  Committee: committeeMapper,
  JobTitle: jobTitleMapper,
  Position: positionMapper,
  ReportingStructure: reportingStructureMapper,
  CostCenter: costCenterMapper,
  KnowledgeDocument: knowledgeDocumentMapper,
  DocumentVersion: documentVersionMapper,
  DocumentApproval: documentApprovalMapper,
  DocumentComment: documentCommentMapper,
  WikiPage: wikiPageMapper,
  WikiRevision: wikiRevisionMapper,
  Note: noteMapper,
  NoteShare: noteShareMapper,
  ResearchPaper: researchPaperMapper,
  ResearchDataset: researchDatasetMapper,
  ResearchProtocol: researchProtocolMapper,
  Citation: citationMapper,
  KnowledgeSource: knowledgeSourceMapper,
  KnowledgeIngestionJob: knowledgeIngestionJobMapper,
  KnowledgeQualityCheck: knowledgeQualityCheckMapper,
  KnowledgeVersion: knowledgeVersionMapper,
  KnowledgeApproval: knowledgeApprovalMapper,
  KnowledgeAutomationRule: knowledgeAutomationRuleMapper,
  KnowledgeAutomationLog: knowledgeAutomationLogMapper,
  AiRequestLog: aiRequestLogMapper,
  AiModel: aiModelMapper,
  AiModelVersion: aiModelVersionMapper,
  AiModelMetric: aiModelMetricMapper,
  AiAgent: aiAgentMapper,
  AiAgentSession: aiAgentSessionMapper,
  AiAgentMessage: aiAgentMessageMapper,
  AiMemory: aiMemoryMapper,
  AiPlan: aiPlanMapper,
  AiPlanStep: aiPlanStepMapper,
  AiReflection: aiReflectionMapper,
  AiTool: aiToolMapper,
  AiToolExecution: aiToolExecutionMapper,
  AiEvaluation: aiEvaluationMapper,
  AiFeedback: aiFeedbackMapper,
  AiAlert: aiAlertMapper,
  AiMetric: aiMetricMapper,
  Comment: commentMapper,
  Discussion: discussionMapper,
  DiscussionReply: discussionReplyMapper,
  ActivityFeed: activityFeedMapper,
  EmailTemplate: emailTemplateMapper,
  EmailLog: emailLogMapper,
  AcademicYear: academicYearMapper,
  Term: termMapper,
  AcademicSection: academicSectionMapper,
  StudentCohort: studentCohortMapper,
  Curriculum: curriculumMapper,
  CurriculumCourse: curriculumCourseMapper,
  DegreeRequirement: degreeRequirementMapper,
  AcademicRegulation: academicRegulationMapper,
  CourseOutcome: courseOutcomeMapper,
  Prerequisite: prerequisiteMapper,
  CourseResource: courseResourceMapper,
  AcademicModule: academicModuleMapper,
  Concept: conceptMapper,
  Topic: topicMapper,
  Lesson: lessonMapper,
  LearningObjective: learningObjectiveMapper,
  Timetable: timetableMapper,
  TimetableSlot: timetableSlotMapper,
  ExaminationSchedule: examinationScheduleMapper,
  CreditRule: creditRuleMapper,
  AcademicStanding: academicStandingMapper,
  GraduationProgress: graduationProgressMapper,
  AcademicResource: academicResourceMapper,
  ReadingList: readingListMapper,
  AcademicPolicy: academicPolicyMapper,
  CourseAllocation: courseAllocationMapper,
  Waitlist: waitlistMapper,
  CourseRegistration: courseRegistrationMapper,
  LearningJourney: learningJourneyMapper,
  LearningMilestone: learningMilestoneMapper,
  DailyLearningGoal: dailyLearningGoalMapper,
  WeeklyLearningGoal: weeklyLearningGoalMapper,
  MonthlyLearningGoal: monthlyLearningGoalMapper,
  FlashcardDeck: flashcardDeckMapper,
  Flashcard: flashcardMapper,
  FlashcardReview: flashcardReviewMapper,
  StudySession: studySessionMapper,
  StudyPlan: studyPlanMapper,
  StudyReminder: studyReminderMapper,
  LearningMemory: learningMemoryMapper,
  KnowledgeGap: knowledgeGapMapper,
  SpacedRepetitionItem: spacedRepetitionItemMapper,
  MasteryPrediction: masteryPredictionMapper,
  LearningStreak: learningStreakMapper,
  ExperiencePoints: experiencePointsMapper,
  LearningChallenge: learningChallengeMapper,
  PeerLearningGroup: peerLearningGroupMapper,
  DigitalCredential: digitalCredentialMapper,
  AcademicTranscript: academicTranscriptMapper,
  AIExplainRequest: aiexplainRequestMapper,
  AIGeneratedQuiz: aigeneratedQuizMapper,
  AIStudyRecommendation: aistudyRecommendationMapper,
  AILearningInsight: ailearningInsightMapper,
  GeneratedQuestion: generatedQuestionMapper,
  ResearchProject: researchProjectMapper,
  ResearchTask: researchTaskMapper,
  ResearchNotebook: researchNotebookMapper,
  ResearchGoal: researchGoalMapper,
  PaperCollection: paperCollectionMapper,
  CitationNetwork: citationNetworkMapper,
  ResearchTrend: researchTrendMapper,
  ResearchSummary: researchSummaryMapper,
  ReadingListResearch: readingListResearchMapper,
  ResearchHypothesis: researchHypothesisMapper,
  ExperimentDesignResearch: experimentDesignResearchMapper,
  PeerReviewRecord: peerReviewRecordMapper,
  Experiment: experimentMapper,
  ExperimentVariable: experimentVariableMapper,
  ExperimentResult: experimentResultMapper,
  ExperimentVersion: experimentVersionMapper,
  ProtocolTemplate: protocolTemplateMapper,
  DatasetVersion: datasetVersionMapper,
  DatasetAnnotation: datasetAnnotationMapper,
  DatasetValidationRule: datasetValidationRuleMapper,
  Publication: publicationMapper,
  SubmissionTracker: submissionTrackerMapper,
  JournalRecommendation: journalRecommendationMapper,
  ReferenceListItem: referenceListItemMapper,
  Patent: patentMapper,
  IdeaSubmission: ideaSubmissionMapper,
  InnovationPipeline: innovationPipelineMapper,
  TechnologyTransfer: technologyTransferMapper,
  GrantOpportunity: grantOpportunityMapper,
  GrantApplication: grantApplicationMapper,
  ResearchTeam: researchTeamMapper,
  ResearchComment: researchCommentMapper,
  ExpertNetwork: expertNetworkMapper,
  PublicationMetric: publicationMetricMapper,
  ResearchImpactScore: researchImpactScoreMapper,
  ResearchFundingMetric: researchFundingMetricMapper,
  CareerProfile: careerProfileMapper,
  CareerGoal: careerGoalMapper,
  InterviewSession: interviewSessionMapper,
  Alumni: alumniMapper,
  AlumniConnection: alumniConnectionMapper,
  MarketplaceListing: marketplaceListingMapper,
  CareerIntelligenceSnapshot: careerIntelligenceSnapshotMapper,
  FacultyProfile: facultyProfileMapper,
  FacultyBriefing: facultyBriefingMapper,
  TeachingPlan: teachingPlanMapper,
  LearningResource: learningResourceMapper,
  ContentItem: contentItemMapper,
  TeachingTimeline: teachingTimelineMapper,
  StudentAlert: studentAlertMapper,
  StudentRecommendation: studentRecommendationMapper,
  FacultyMentee: facultyMenteeMapper,
  AdvisingSession: advisingSessionMapper,
  GoalTracking: goalTrackingMapper,
  FacultyPublication: facultyPublicationMapper,
  FacultyCertification: facultyCertificationMapper,
  FacultyAward: facultyAwardMapper,
  FacultyWorkshop: facultyWorkshopMapper,
  FacultyTraining: facultyTrainingMapper,
  DepartmentDiscussion: departmentDiscussionMapper,
  SharedResource: sharedResourceMapper,
  FacultyWorkload: facultyWorkloadMapper,
  LeaveRequest: leaveRequestMapper,
  FacultyTimetable: facultyTimetableMapper,
  CommitteeAssignment: committeeAssignmentMapper,
  FacultyNote: facultyNoteMapper,
  FacultyBookmark: facultyBookmarkMapper,
  SavedPrompt: savedPromptMapper,
  Prediction: predictionMapper,
  IntelligenceRecommendation: intelligenceRecommendationMapper,
  DataQualityRecord: dataQualityRecordMapper,
  DataLineageRecord: dataLineageRecordMapper,
  BenchmarkRecord: benchmarkRecordMapper,
  IntelligenceReport: intelligenceReportMapper,
  WhiteLabelConfig: whiteLabelConfigMapper,
  InstitutionCollaboration: institutionCollaborationMapper,
  BetaProgram: betaProgramMapper,
  BetaEnrollment: betaEnrollmentMapper,
  LocalizationEntry: localizationEntryMapper,
  OrgAcademicCalendar: orgAcademicCalendarMapper,
  OrgSemester: orgSemesterMapper,
  StudentEvent: studentEventMapper,
  CompetencyEvidence: competencyEvidenceMapper,
  AIRecommendation: airecommendationMapper,
  AITutoringSession: aitutoringSessionMapper,
  AIContentGeneration: aicontentGenerationMapper,
  StudentLearningProfile: studentLearningProfileMapper,
  AIInterventionCampaign: aiinterventionCampaignMapper,
  AdaptiveDifficultyLevel: adaptiveDifficultyLevelMapper,
  ResumeAiReview: resumeAiReviewMapper,
  OntologyVersion: ontologyVersionMapper,
  SuccessMetrics: successMetricsMapper,
  StudentGoal: studentGoalMapper,
  ProductivitySession: productivitySessionMapper,
  RiskIndicator: riskIndicatorMapper,
  ReadinessAssessment: readinessAssessmentMapper,
  StudentAchievement: studentAchievementMapper,
  StudentTask: studentTaskMapper,
  SimulationScenario: simulationScenarioMapper,
  CapstoneProject: capstoneProjectMapper,
  SuccessCoachSession: successCoachSessionMapper,
  JobApplication: jobApplicationMapper,
  JobOffer: jobOfferMapper,
  Placement: placementMapper,
  ProfessionalNetwork: professionalNetworkMapper,
  NetworkingEvent: networkingEventMapper,
  FundingApplication: fundingApplicationMapper,
  CareerDevelopmentPlan: careerDevelopmentPlanMapper,
  CareerResourceAccess: careerResourceAccessMapper,
  CareerAIInsight: careerAiinsightMapper,
  CareerMockInterview: careerMockInterviewMapper,
  JobAlertSubscription: jobAlertSubscriptionMapper,
};

/** Get a mapper for an entity type */
export function getMapper(entityType: string): RdfMapper | undefined {
  return mapperRegistry[entityType];
}

/** Get all registered entity types */
export function getEntityTypes(): string[] {
  return Object.keys(mapperRegistry);
}

/** Register a new mapper */
export function registerMapper(entityType: string, mapper: RdfMapper): void {
  mapperRegistry[entityType] = mapper;
}
