"use client";

/**
 * Decision Inbox — Faculty review hub (BRD SVC-08, FR-009/010/011).
 * ===========================================================================
 * Real-time polling ensures the inbox always reflects the current DB state.
 * When slides are being generated or regenerated, the inbox updates live.
 *
 * Key features:
 *   - Polls every 5s when there are pending items (10s when empty)
 *   - Shows live status for items being generated/regenerating
 *   - Approve All with real-time progress feedback
 *   - Rich context per item: slide preview, source evidence, gate details
 *   - Proper cache invalidation after every mutation
 */

import { use, useState, useMemo, useEffect, useCallback } from "react";
import Link from "next/link";
import { notFound, useRouter } from "next/navigation";
import { useApiQuery, useApiMutation } from "@/lib/use-api-query";
import { useApp } from "@/lib/store";
import { PageHeader } from "@/components/iscarb/PageHeader";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { InboxItem, type DecisionItem } from "@/components/lecture/InboxItem";
import {
  CheckCircle2,
  Inbox,
  AlertTriangle,
  ArrowRight,
  ShieldCheck,
  Layers,
  Filter,
  Sparkles,
  RefreshCw,
  Loader2,
  Clock,
  Zap,
} from "lucide-react";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface InboxResponse {
  pending: DecisionItem[];
  resolved: DecisionItem[];
  totalPending: number;
  /** Items currently being generated/regenerated by background workers. */
  generating?: Array<{
    slideNo: number;
    status: string;
    progress?: number;
  }>;
  /** Project-level status (generating, review, etc.) */
  projectStatus?: string;
}

interface ActVars {
  artifactId: string;
  action: string;
  reason?: string;
  editedContent?: unknown;
}

// ---------------------------------------------------------------------------
// Polling config
// ---------------------------------------------------------------------------

const POLL_INTERVAL_ACTIVE = 5_000;  // 5s when there are pending items
const POLL_INTERVAL_IDLE = 15_000;   // 15s when inbox is clean

// ---------------------------------------------------------------------------
// Page Component
// ---------------------------------------------------------------------------

export default function InboxPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const { lang } = useApp();
  const ar = lang === "ar";
  const router = useRouter();
  const [filterType, setFilterType] = useState<string>("all");

  // ── Real-time polling ──────────────────────────────────────────────────
  const { data, isLoading, error, refetch, dataUpdatedAt } = useApiQuery<InboxResponse>(
    ["lecture", "inbox", id],
    `/api/iscarb/lecture/projects/${id}/decisions/inbox`,
    {
      staleTime: 0,
      // Poll faster when there are pending items, slower when clean
      refetchInterval: (query: { state: { data?: InboxResponse } }) => {
        const pending = query.state.data?.pending;
        if (pending && pending.length > 0) return POLL_INTERVAL_ACTIVE;
        return POLL_INTERVAL_IDLE;
      },
    },
  );

  // ── Mutations ──────────────────────────────────────────────────────────
  const act = useApiMutation<{ decisionId: string }, ActVars>(
    (vars) => `/api/iscarb/lecture/artifacts/${vars.artifactId}/decisions`,
    {
      invalidateKeys: () => [
        ["lecture", "inbox", id],
        ["lecture", "artifacts", id],
        ["lecture", "gates", id],
        ["lecture", "quality", id],
      ],
      onSuccess: () => {
        // Force immediate refetch after any action
        setTimeout(() => refetch(), 200);
      },
    },
  );

  const alignAct = useApiMutation<{ linkId: string }, { linkId: string; action: string; reason?: string }>(
    (vars) => `/api/iscarb/lecture/alignment-links/${vars.linkId}/decision`,
    {
      invalidateKeys: () => [
        ["lecture", "inbox", id],
        ["lecture", "matrix", id],
      ],
      onSuccess: () => {
        setTimeout(() => refetch(), 200);
      },
    },
  );

  const approveAll = useApiMutation<{ success: boolean; approvedCount: number }, Record<string, never>>(
    `/api/iscarb/lecture/projects/${id}/decisions/inbox`,
    {
      method: "POST",
      invalidateKeys: () => [
        ["lecture", "inbox", id],
        ["lecture", "artifacts", id],
        ["lecture", "matrix", id],
        ["lecture", "quality", id],
        ["lecture", "gates", id],
      ],
      onSuccess: () => {
        setTimeout(() => refetch(), 300);
      },
    },
  );

  // ── Error handling ─────────────────────────────────────────────────────
  if (!isLoading && error && !data) {
    if (error.message.includes("404")) notFound();
  }

  const pending = data?.pending ?? [];
  const resolved = data?.resolved ?? [];
  const generating = data?.generating ?? [];
  const projectStatus = data?.projectStatus;
  const pendingSlides = pending.filter((p) => p.type === "artifact");
  const isGenerating = projectStatus === "generating" || generating.length > 0;

  // ── Handlers ───────────────────────────────────────────────────────────
  const handleApproveAllSlides = () => {
    if (pending.length === 0) return;
    const ok = window.confirm(
      ar
        ? `اعتماد كافة القرارات المعلقة (${pending.length} عنصر)؟`
        : `Approve all ${pending.length} pending items? This action cannot be undone.`
    );
    if (!ok) return;
    approveAll.mutate({});
  };

  const filteredPending = useMemo(() => {
    if (filterType === "all") return pending;
    return pending.filter((item) => item.type === filterType);
  }, [pending, filterType]);

  const handleAction = (item: DecisionItem, action: string, reason?: string) => {
    if (item.type === "alignment") {
      const mapped = action === "approve" || action === "accept" ? "accept" : "reject";
      void alignAct.mutate({ linkId: item.id, action: mapped, reason });
      return;
    }
    void act.mutate({
      action,
      reason,
      ...(action === "edit" ? { editedContent: undefined } : {}),
      artifactId: item.id,
    });
  };

  // ── Time since last update ─────────────────────────────────────────────
  const [timeSinceUpdate, setTimeSinceUpdate] = useState("");
  useEffect(() => {
    if (!dataUpdatedAt) return;
    const tick = () => {
      const secs = Math.round((Date.now() - dataUpdatedAt) / 1000);
      if (secs < 5) setTimeSinceUpdate(ar ? "الآن" : "Just now");
      else if (secs < 60) setTimeSinceUpdate(ar ? `منذ ${secs}ث` : `${secs}s ago`);
      else setTimeSinceUpdate(ar ? `منذ ${Math.floor(secs / 60)}د` : `${Math.floor(secs / 60)}m ago`);
    };
    tick();
    const timer = setInterval(tick, 5_000);
    return () => clearInterval(timer);
  }, [dataUpdatedAt, ar]);

  // ── Filter categories ──────────────────────────────────────────────────
  const filterCategories = useMemo(() => [
    { id: "all", labelEn: "All Items", labelAr: "كل القرارات", count: pending.length, icon: Inbox },
    { id: "artifact", labelEn: "Slides", labelAr: "الشرائح", count: pendingSlides.length, icon: Layers },
    { id: "claim", labelEn: "Quality Gates", labelAr: "بوابات الجودة", count: pending.filter((p) => p.type === "claim").length, icon: ShieldCheck },
    { id: "alignment", labelEn: "Jaheziah", labelAr: "جاهزية", count: pending.filter((p) => p.type === "alignment").length, icon: Filter },
    { id: "coverage", labelEn: "Source", labelAr: "المصدر", count: pending.filter((p) => p.type === "coverage").length, icon: Filter },
  ], [pending, pendingSlides]);

  return (
    <div className="space-y-8 pb-32">
      <PageHeader
        title={ar ? "صندوق القرارات" : "Decision Inbox"}
        description={
          isGenerating
            ? ar
              ? "النظام يعمل حالياً — يتم تحديث القائمة تلقائياً."
              : "Live — inbox updates automatically while content generates."
            : ar
              ? "راجع الشرائح والمواءمة وبوابات الجودة قبل النشر."
              : "Review draft/flagged slides, quality gates, and alignment before publishing."
        }
        breadcrumbs={[
          { label: ar ? "محاضراتي" : "My Lectures", href: "/faculty/lecture" },
          { label: ar ? "صندوق القرارات" : "Decision Inbox" },
        ]}
        actions={
          pending.length > 0 ? (
            <div className="flex items-center gap-3">
              {/* Live indicator */}
              <div className="flex items-center gap-2 text-xs text-slate-500 font-medium">
                <span className="relative flex h-2 w-2">
                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75" />
                  <span className="relative inline-flex rounded-full h-2 w-2 bg-emerald-500" />
                </span>
                {timeSinceUpdate}
              </div>
              <Button
                onClick={handleApproveAllSlides}
                disabled={approveAll.isPending}
                className="bg-[#0E6C3C] hover:bg-[#0E6C3C]/90 text-white font-extrabold shadow-lg shadow-[#0E6C3C]/20 rounded-xl px-6 py-5 text-sm"
              >
                {approveAll.isPending ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    {ar ? "جاري الاعتماد..." : "Approving..."}
                  </>
                ) : (
                  <>
                    <CheckCircle2 className="mr-2 h-4 w-4" />
                    {ar ? "اعتماد الكل" : "Approve All"} ({pending.length})
                  </>
                )}
              </Button>
            </div>
          ) : undefined
        }
      />

      {isLoading && (
        <div className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {[1, 2, 3].map((i) => (
              <Skeleton key={i} className="h-24 rounded-2xl" />
            ))}
          </div>
          <Skeleton className="h-48 rounded-2xl" />
        </div>
      )}

      {data && (
        <>
          {/* ── Summary Metric Cards ──────────────────────────────────────── */}
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <Card className={`border-border/50 shadow-sm ${isGenerating ? "ring-2 ring-emerald-500/30" : ""}`}>
              <CardContent className="p-4 flex items-center justify-between">
                <div>
                  <p className="text-3xl font-display font-bold tabular-nums text-amber-600 dark:text-amber-400">
                    {pending.length}
                  </p>
                  <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground mt-0.5">
                    {ar ? "معلّق" : "Pending"}
                  </p>
                </div>
                <div className="relative">
                  <AlertTriangle className="h-8 w-8 text-amber-500/30" />
                  {isGenerating && (
                    <span className="absolute -top-1 -right-1 flex h-3 w-3">
                      <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75" />
                      <span className="relative inline-flex rounded-full h-3 w-3 bg-emerald-500" />
                    </span>
                  )}
                </div>
              </CardContent>
            </Card>

            <Card className="border-border/50 shadow-sm">
              <CardContent className="p-4 flex items-center justify-between">
                <div>
                  <p className="text-3xl font-display font-bold tabular-nums text-emerald-600 dark:text-emerald-400">
                    {resolved.length}
                  </p>
                  <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground mt-0.5">
                    {ar ? "معتمد" : "Resolved"}
                  </p>
                </div>
                <CheckCircle2 className="h-8 w-8 text-emerald-500/30" />
              </CardContent>
            </Card>

            <Card className="border-border/50 shadow-sm">
              <CardContent className="p-4 flex items-center justify-between">
                <div>
                  <p className="text-3xl font-display font-bold tabular-nums text-[#0F7B8A]">
                    {pending.length === 0 ? "100%" : `${Math.round((resolved.length / ((pending.length + resolved.length) || 1)) * 100)}%`}
                  </p>
                  <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground mt-0.5">
                    {ar ? "الجاهزية" : "Quality Score"}
                  </p>
                </div>
                <ShieldCheck className="h-8 w-8 text-[#0F7B8A]/30" />
              </CardContent>
            </Card>

            {/* Live Status Card */}
            <Card className={`border-border/50 shadow-sm ${isGenerating ? "bg-emerald-500/5 border-emerald-500/30" : ""}`}>
              <CardContent className="p-4 flex items-center justify-between">
                <div>
                  {isGenerating ? (
                    <>
                      <p className="text-sm font-bold text-emerald-600 flex items-center gap-2">
                        <Loader2 className="h-4 w-4 animate-spin" />
                        {ar ? "قيد التوليد" : "Generating"}
                      </p>
                      <p className="text-xs font-medium text-muted-foreground mt-0.5">
                        {generating.length > 0
                          ? ar
                            ? `${generating.length} شريحة قيد المعالجة`
                            : `${generating.length} slide${generating.length > 1 ? "s" : ""} processing`
                          : ar
                            ? "النظام يعمل..."
                            : "Workers active"}
                      </p>
                    </>
                  ) : (
                    <>
                      <p className="text-sm font-bold text-slate-500">
                        {ar ? "جاهز" : "Idle"}
                      </p>
                      <p className="text-xs font-medium text-muted-foreground mt-0.5">
                        {ar ? "لا يوجد توليد نشط" : "No active generation"}
                      </p>
                    </>
                  )}
                </div>
                {isGenerating ? (
                  <div className="p-2.5 rounded-xl bg-emerald-500/10 border border-emerald-500/30">
                    <Zap className="h-5 w-5 text-emerald-600 animate-pulse" />
                  </div>
                ) : (
                  <div className="p-2.5 rounded-xl bg-slate-100 dark:bg-slate-800">
                    <Clock className="h-5 w-5 text-slate-400" />
                  </div>
                )}
              </CardContent>
            </Card>
          </div>

          {/* ── ALL RESOLVED CELEBRATION ──────────────────────────────────── */}
          {pending.length === 0 && !isGenerating && (
            <Card className="border border-emerald-500/40 bg-gradient-to-br from-emerald-500/10 via-background to-teal-500/10 shadow-xl rounded-2xl overflow-hidden">
              <CardContent className="flex flex-col items-center justify-center text-center p-10 space-y-4">
                <div className="p-4 rounded-full bg-emerald-500/20 text-emerald-600 shadow-inner">
                  <CheckCircle2 className="h-12 w-12" />
                </div>
                <div className="space-y-1 max-w-md">
                  <h3 className="text-2xl font-display font-extrabold text-foreground">
                    {ar ? "جميع القرارات مكتملة!" : "All Decisions Resolved!"}
                  </h3>
                  <p className="text-sm text-muted-foreground">
                    {ar
                      ? "المحتوى والمواءمة مطابقان لكافة المعايير. جاهز للنشر."
                      : "Content and alignment comply with all quality standards. Ready to publish."}
                  </p>
                </div>
                <Button
                  onClick={() => router.push(`/faculty/lecture/${id}/publish`)}
                  className="bg-[#0E6C3C] hover:bg-[#0E6C3C]/90 text-white shadow-lg shadow-[#0E6C3C]/20 px-8 py-6 rounded-xl text-base font-bold mt-2"
                >
                  {ar ? "الانتقال للنشر" : "Continue to Publish"} <ArrowRight className="ml-2 h-5 w-5" />
                </Button>
              </CardContent>
            </Card>
          )}

          {/* ── GENERATING PROGRESS ───────────────────────────────────────── */}
          {isGenerating && generating.length > 0 && (
            <Card className="border border-emerald-500/30 bg-emerald-500/5 shadow-sm rounded-2xl">
              <CardContent className="p-4">
                <div className="flex items-center gap-3 mb-3">
                  <Loader2 className="h-5 w-5 text-emerald-600 animate-spin" />
                  <span className="text-sm font-bold text-emerald-700 dark:text-emerald-300">
                    {ar ? "جاري توليد المحتوى..." : "Content generation in progress..."}
                  </span>
                </div>
                <div className="flex flex-wrap gap-2">
                  {generating.map((g) => (
                    <Badge
                      key={g.slideNo}
                      variant="outline"
                      className="bg-emerald-500/10 text-emerald-700 dark:text-emerald-300 border-emerald-500/30 text-xs"
                    >
                      S{g.slideNo}
                      {g.progress != null && (
                        <span className="ml-1 opacity-70">{g.progress}%</span>
                      )}
                    </Badge>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}

          {/* ── PENDING ITEMS ─────────────────────────────────────────────── */}
          {pending.length > 0 && (
            <div className="space-y-6">
              <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 border-b border-slate-200/60 dark:border-slate-800 pb-4">
                <div className="flex items-center gap-3">
                  <div className="p-2.5 rounded-xl bg-amber-500/10 text-amber-600 border border-amber-500/30">
                    <AlertTriangle className="h-5 w-5" />
                  </div>
                  <div>
                    <h2 className="text-lg font-display font-black text-slate-900 dark:text-white">
                      {ar ? "تتطلب قراراً" : "Needs Decision"} ({pending.length})
                    </h2>
                    <p className="text-xs text-slate-500 font-medium mt-0.5">
                      {ar ? "اختر إجراء لكل عنصر." : "Choose an action for each item."}
                    </p>
                  </div>
                </div>

                <div className="flex items-center gap-2 overflow-x-auto w-full sm:w-auto">
                  <span className="text-xs font-extrabold text-slate-400 uppercase tracking-wider mr-1">{ar ? "تصفية:" : ""}</span>
                  {filterCategories.map((f) => {
                    const Icon = f.icon;
                    return (
                      <Button
                        key={f.id}
                        variant={filterType === f.id ? "default" : "outline"}
                        size="sm"
                        onClick={() => setFilterType(f.id)}
                        className={
                          filterType === f.id
                            ? "bg-slate-900 dark:bg-white text-white dark:text-slate-900 font-extrabold text-xs h-9 rounded-xl shadow-sm"
                            : "text-slate-600 dark:text-slate-400 text-xs h-9 rounded-xl border-slate-200 dark:border-slate-800"
                        }
                      >
                        {ar ? f.labelAr : f.labelEn}
                        {f.count > 0 && (
                          <Badge className="ml-1.5 bg-slate-200 dark:bg-slate-800 text-slate-900 dark:text-white font-mono text-[10px] px-1.5 py-0.2">
                            {f.count}
                          </Badge>
                        )}
                      </Button>
                    );
                  })}
                </div>
              </div>

              <div className="space-y-4">
                {filteredPending.map((item) => (
                  <InboxItem
                    key={item.id}
                    item={item}
                    busy={act.isPending || alignAct.isPending}
                    onAction={(action, reason) => handleAction(item, action, reason)}
                  />
                ))}
              </div>
            </div>
          )}

          {/* ── RESOLVED HISTORY ──────────────────────────────────────────── */}
          {resolved.length > 0 && (
            <div className="space-y-4 pt-6 border-t">
              <div className="flex items-center justify-between">
                <h3 className="text-sm font-bold text-muted-foreground uppercase tracking-wider flex items-center gap-2">
                  <CheckCircle2 className="h-4 w-4 text-emerald-500" />
                  {ar ? "القرارات المعتمدة" : "Resolved"} ({resolved.length})
                </h3>
                <button
                  onClick={() => refetch()}
                  className="text-xs text-slate-400 hover:text-slate-600 flex items-center gap-1"
                >
                  <RefreshCw className="h-3 w-3" />
                  {ar ? "تحديث" : "Refresh"}
                </button>
              </div>
              <div className="space-y-3 opacity-75">
                {resolved.map((item) => (
                  <InboxItem
                    key={item.id}
                    item={item}
                    busy={false}
                    onAction={() => {}}
                  />
                ))}
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
}
