import { NextResponse } from 'next/server';
import { jsonLdEngine } from '@/lib/kg/engine';

export async function GET(
  request: Request,
  { params }: { params: { domain: string, id: string } }
) {
  try {
    const { domain, id } = params;
    const url = new URL(request.url);
    const expand = url.searchParams.get('expand') === 'true';

    // A simple registry mapping route domains to Prisma model names
    // This could be automatically generated by the kg-framework in the future
    const modelRegistry: Record<string, string> = {
      'user': 'user',
      'student': 'student',
      'course': 'course',
      'faculty': 'faculty',
      'job': 'jobPosting',
      'competency': 'competencyDefinition',
      'assessment': 'assessmentModule',
      'university': 'university'
    };

    const modelName = modelRegistry[domain];
    
    if (!modelName) {
      return NextResponse.json({ error: `Domain '${domain}' is not mapped to an API route.` }, { status: 404 });
    }

    const payload = await jsonLdEngine.serialize(domain, modelName, id, expand);

    if (!payload) {
      return NextResponse.json({ error: `Entity not found` }, { status: 404 });
    }

    return NextResponse.json(payload, {
      headers: {
        'Content-Type': 'application/ld+json',
        'Access-Control-Allow-Origin': '*'
      }
    });
  } catch (error: any) {
    console.error(`[RDF-API] Error generating JSON-LD:`, error);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}
